version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: monthly
    time: "02:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: database_cleaner
    versions:
    - 1.8.5
    - 2.0.0
  - dependency-name: newrelic_rpm
    versions:
    - 6.14.0
  - dependency-name: loofah
    versions:
    - 2.8.0
