# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 88912817c5fc2f30a74f03733b2fabcddf111c80adda50594e943fcf99a5846b364435d7c4128860df8c576ce215144f8215021655e0bf778de9c26c7d10e8dd

test:
  secret_key_base: 78e9bfcb04c41fc875da210c4e6c3cbbb64d5b09d4c81006ad558f6014c1fe72ee074f9d7374c08f452f2691cc63fdcb9b87b636a905cc70778a87698dc4e851

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
